# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/compiler/xla/service/gpu/gpu_autotuning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.compiler.xla.service import hlo_pb2 as tensorflow_dot_compiler_dot_xla_dot_service_dot_hlo__pb2
from tensorflow.compiler.xla import xla_data_pb2 as tensorflow_dot_compiler_dot_xla_dot_xla__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/compiler/xla/service/gpu/gpu_autotuning.proto',
  package='xla.gpu',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n8tensorflow/compiler/xla/service/gpu/gpu_autotuning.proto\x12\x07xla.gpu\x1a)tensorflow/compiler/xla/service/hlo.proto\x1a&tensorflow/compiler/xla/xla_data.proto\"\x9f\x01\n\x12\x43onvInstructionLog\x12-\n\x0binstruction\x18\x01 \x01(\x0b\x32\x18.xla.HloInstructionProto\x12\'\n\x0eoperand_shapes\x18\x02 \x03(\x0b\x32\x0f.xla.ShapeProto\x12\x16\n\x0eresult_address\x18\x03 \x01(\x04\x12\x19\n\x11operand_addresses\x18\x04 \x03(\x04\x62\x06proto3')
  ,
  dependencies=[tensorflow_dot_compiler_dot_xla_dot_service_dot_hlo__pb2.DESCRIPTOR,tensorflow_dot_compiler_dot_xla_dot_xla__data__pb2.DESCRIPTOR,])




_CONVINSTRUCTIONLOG = _descriptor.Descriptor(
  name='ConvInstructionLog',
  full_name='xla.gpu.ConvInstructionLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instruction', full_name='xla.gpu.ConvInstructionLog.instruction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operand_shapes', full_name='xla.gpu.ConvInstructionLog.operand_shapes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_address', full_name='xla.gpu.ConvInstructionLog.result_address', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operand_addresses', full_name='xla.gpu.ConvInstructionLog.operand_addresses', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=312,
)

_CONVINSTRUCTIONLOG.fields_by_name['instruction'].message_type = tensorflow_dot_compiler_dot_xla_dot_service_dot_hlo__pb2._HLOINSTRUCTIONPROTO
_CONVINSTRUCTIONLOG.fields_by_name['operand_shapes'].message_type = tensorflow_dot_compiler_dot_xla_dot_xla__data__pb2._SHAPEPROTO
DESCRIPTOR.message_types_by_name['ConvInstructionLog'] = _CONVINSTRUCTIONLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConvInstructionLog = _reflection.GeneratedProtocolMessageType('ConvInstructionLog', (_message.Message,), {
  'DESCRIPTOR' : _CONVINSTRUCTIONLOG,
  '__module__' : 'tensorflow.compiler.xla.service.gpu.gpu_autotuning_pb2'
  # @@protoc_insertion_point(class_scope:xla.gpu.ConvInstructionLog)
  })
_sym_db.RegisterMessage(ConvInstructionLog)


# @@protoc_insertion_point(module_scope)
