config: {
    name:  "ods_objdet",
    base_path:  "/models/ods_objdet",
    model_platform: "tensorflow",
    model_version_policy: {
      specific: { 
        versions: 1
      }
    }
  }
  config: {
    name:  "ods_cls",
    base_path:  "/models/ods_cls",
    model_platform: "tensorflow",
    model_version_policy: {
      specific: { 
        versions: [1, 2, 3]
      }
    }
  }
